name: alrehila
description: A new app that help people to visit the arab world.
publish_to: 'none'
version: 2024.8.27+12

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core_platform_interface: ^5.2.0
  curved_labeled_navigation_bar: ^2.0.2
  flutter_local_notifications: ^17.2.2
  firebase_in_app_messaging: ^0.8.0+4
  esys_flutter_share_plus: ^2.2.0
  flutter_datetime_picker: ^1.5.1
  flutter_animated_button: ^2.0.3
  firebase_performance: ^0.10.0+4
  firebase_remote_config: ^5.0.4
  flutter_native_splash: ^2.4.1
  curved_navigation_bar: ^1.0.6
  flutter_facebook_auth: ^7.0.1
  flutter_email_sender: ^6.0.1
  flutter_inappwebview: ^6.0.0
  cached_network_image: ^3.2.3
  firebase_app_check: ^0.3.0+4
  firebase_messaging: ^15.0.4
  permission_handler: ^11.1.0
  shared_preferences: ^2.3.1
  salomon_bottom_bar: ^3.3.2
  package_info_plus: ^8.0.2
  flutter_customs: ^0.0.28
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.2.2
  google_sign_in: ^6.2.1
  otp_text_field: ^1.1.3
  path_provider: ^2.0.15
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  image_cropper: ^8.0.1
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  home_widget: ^0.3.1
  share_plus: ^10.0.0
  translator: ^1.0.0
  rename_app: ^1.6.1
  readmore: ^3.0.0
  shimmer: ^3.0.0
  lottie: ^3.0.0
  dartz: ^0.10.1
  intl: 0.19.0
  path: ^1.9.0
  http: ^1.2.2
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.3.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/newicon5.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  color_dark: "#161616"
  image_dark: assets/images/splash.png

  android_12:
    color: "#FFFFFF"
    image: assets/images/splash.png
    color_dark: "#161616"
    image_dark: assets/images/splash.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-BlackItalic.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-BoldItalic.ttf
        - asset: assets/fonts/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
        - asset: assets/fonts/Nunito-ExtraLight.ttf
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
        - asset: assets/fonts/Nunito-Light.ttf
        - asset: assets/fonts/Nunito-LightItalic.ttf
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
