// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYO9i53PS67Jd-s2IVYp4msnGSYiaWEGw',
    appId: '1:653678569175:android:8e7523092810b8af857292',
    messagingSenderId: '653678569175',
    projectId: 'alrehila-0',
    storageBucket: 'alrehila-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBCRVVmnCVaXEDwGGjiIwK2tbKJNs5n2M',
    appId: '1:653678569175:ios:a0cefc7f52c7a6d0857292',
    messagingSenderId: '653678569175',
    projectId: 'alrehila-0',
    storageBucket: 'alrehila-0.appspot.com',
    androidClientId: '653678569175-0cjn94alqqr6oardsh85b7m1bge1dkav.apps.googleusercontent.com',
    iosClientId: '653678569175-g10jgm1ajlddjkc3jgvlgl47c43e155j.apps.googleusercontent.com',
    iosBundleId: 'com.elmoparmg.alrehila',
  );

}